services:
  userserver:
    image: ${DOCKER_REGISTRY-}userserver
    build:
      context: .
      dockerfile: UserServer/Dockerfile
    ports:
      - "5000:8080"
      #- "5035:8081" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_DBUSER=${ASPNETCORE_DBUSER}
      - ASPNETCORE_DBPASSWORD=${ASPNETCORE_DBPASSWORD}
      - ASPNETCORE_DBBASE=${ASPNETCORE_DBBASE}
      - ASPNETCORE_REDIS_PASSWORD=${ASPNETCORE_REDIS_PASSWORD}
      - ASPNETCORE_REDISPORT=${ASPNETCORE_REDISPORT}
      - ASPNETCORE_RABITPROT=${ASPNETCORE_RABITPROT} 
      - ASPNETCORE_RABIT_USER=${ASPNETCORE_RABIT_USER}
      - ASPNETCORE_RABIT_PASSWORD=${ASPNETCORE_RABIT_PASSWORD}
      - ASPNETCORE_RABIT_VHOST=${ASPNETCORE_RABIT_VHOST} 
    depends_on:
    - postgresDBUsers  
  postgresDBUsers:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${ASPNETCORE_DBBASE}
      POSTGRES_USER: ${ASPNETCORE_DBUSER}
      POSTGRES_PASSWORD: ${ASPNETCORE_DBPASSWORD}
    ports:
      - "5432:${ASPNETCORE_DBPORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:

networks:
  default:
    name: "BestNetwoks"  
